### ISSUE TITLE
regex for [airline , flightnumber] issue

### ISSUE THREAD

**Issue by feydreva** [jeremybmerrill/flyover#5]
Hello, 

you use the regex : 

flight_number_re = re.compile("^([A-Z]+)?(\d+)$")
airline, number = flight_number_re.match(flight_number).groups()

to separate the Airline code from the Flight number
which works great for flight like AAA123.

But it seems to fails for airline code like VOE26P or VOE2KM, when there is letter in the flight number.
How can I modify this ?

**Comment by jeremybmerrill** [comment]
Hi, great question. I'm happy to see you're interested in this project.

This should work:
```
flight_number_re = re.compile("^([A-Z]{3})?(\d[A-Z0-9]*)$")
airline, number = flight_number_re.match(flight_number).groups()
```

**Comment by feydreva** [comment]
Thank you ! :) that s good.
I just learning Python, and could not figure this out :/

**Comment by jeremybmerrill** [comment]
Happy to help! (Regular expressions are very hard, very unintuitive.)
